/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#46484d",
        "inverse-primary": "#006976",
        "on-tertiary-fixed": "#331f00",
        "surface-bright": "#292c33",
        "on-primary": "#005762",
        "primary-fixed-dim": "#00d4ec",
        "primary": "#81ecff",
        "secondary-container": "#006e16",
        "secondary-fixed": "#00fc40",
        "tertiary-fixed-dim": "#ec9e00",
        "surface-container": "#171a1f",
        "surface-container-high": "#1d2025",
        "inverse-surface": "#f9f9ff",
        "error-container": "#9f0519",
        "tertiary-container": "#feaa00",
        "outline": "#74757a",
        "on-secondary-fixed": "#00440a",
        "tertiary": "#ffbd5c",
        "surface-container-lowest": "#000000",
        "on-secondary-container": "#e6ffdc",
        "secondary-dim": "#00ec3b",
        "on-tertiary-container": "#503300",
        "tertiary-dim": "#ec9e00",
        "primary-dim": "#00d4ec",
        "on-primary-container": "#004d57",
        "on-surface-variant": "#aaabb0",
        "on-surface": "#f6f6fc",
        "inverse-on-surface": "#53555a",
        "on-error": "#490006",
        "surface-container-highest": "#23262c",
        "surface-container-low": "#111318",
        "error-dim": "#d7383b",
        "secondary": "#00fc40",
        "surface-tint": "#81ecff",
        "on-secondary-fixed-variant": "#006513",
        "surface-dim": "#0c0e12",
        "on-background": "#f6f6fc",
        "surface": "#0c0e12",
        "on-error-container": "#ffa8a3",
        "secondary-fixed-dim": "#00ec3b",
        "on-tertiary-fixed-variant": "#5b3b00",
        "on-primary-fixed-variant": "#005762",
        "background": "#0c0e12",
        "primary-container": "#00e3fd",
        "error": "#ff716c",
        "tertiary-fixed": "#feaa00",
        "surface-variant": "#23262c",
        "primary-fixed": "#00e3fd",
        "on-primary-fixed": "#003840",
        "on-tertiary": "#5c3b00",
        "on-secondary": "#005a10",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
